const defaultOptions = {
    wrapper: false,
    activeSlide: 0,
    slidesToShow: 4,
    slidesToScroll: 1,
    autoPlay: false,
    autoPlayDelay: 2,
    animationSpeed: 1,
    stopAnimation: true,
    draggable: true,
    arrowsView: true,
    arrowsTemplate: '<a href="#"></a>',
    dotsView: true,
    dotsTemplate: '<a href="#"></a>',
    dotsImageView: false,
    dotsSize: '20x20',
    infinity: true,
    autoInit: true,
    afterChange: null,
    beforeChange: null,
    onArrow: null,
    navigateKeyboard: true,
    defaultClass: 'slider-my',
    initSlider: 'slider-init',
    customSliderClass: '',
    arrowsClass: 'slider-arrow',
    customArrowsClass: '',
    dotsClass: 'slider-dots',
    dotsImageClass: 'dots-image',
    customDotsClass: '',
    sliderListClass: 'slider-list',
    sliderTrackClass: 'slider-track',
};

export default defaultOptions;
