const defaultOptions = {
    wrapper: document.querySelector('body'),
    storageKey: 'formBuilder',
    formClass: 'formBuilder',
    inputDefaultClass: 'form-builder-input',
    elements: {
        label: ['for'],
        input: [
            'button',
            'checkbox',
            'file',
            'image',
            'password',
            'radio',
            'reset',
            'submit',
            'text',
            'color',
            'date',
            'datetime',
            'datetime-local',
            'email',
            'number',
            'range',
            'search',
            'tel',
            'time',
            'url',
            'month',
            'week',
        ],
        select: [
            'size',
            'multiple',
        ],
        textarea: [],
        button: [
            'button',
            'reset',
            'submit',
        ],
    },
    attrElemForm: {
        globalAttr: [
            'type',
            'name',
            'hidden',
            'value',
            'readonly',
            'disabled',
            'maxlength',
            'min',
            'max',
            'pattern',
            'multiple',
            'placeholder',
            'required',
            'step',
            'autofocus',
            'autocomplete',
            'selected',
        ],
        html: ['id', 'className', 'customAttr'],
    },
    mode: 'admin',
    form: ['action', 'autocomplete', 'method', 'name'],
};

export default defaultOptions;
