const elementForm = {
    elements: [
        'input',
        'select',
        'textarea',
        'button',
    ],
    type: [
        'button',
        'checkbox',
        'file',
        'image',
        'password',
        'radio',
        'reset',
        'submit',
        'text',
        'color',
        'date',
        'datetime',
        'datetime-local',
        'email',
        'number',
        'range',
        'search',
        'tel',
        'time',
        'url',
        'month',
        'week',
    ],
    formAttr: [
        'name',
        'hidden',
        'value',
        'readonly',
        'disabled',
        'maxlength',
        'min',
        'max',
        'pattern',
        'multiple',
        'placeholder',
        'required',
        'step',
        'autofocus',
        'autocomplete',
        'selected',
        'size',
        'custom',
        'validate'
    ]
};

export default elementForm;
